name: Test Auto-PR & Merge

# Manuelles Auslösen und zusätzlich alle 5 Minuten (zum Testen)
on:
  workflow_dispatch:

permissions:
  contents: write           # für checkout & commit
  pull-requests: write      # für PR erstellen und mergen

jobs:
  generate-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate or update files
        run: |
          # Beispiel: Timestamp aktualisieren
          echo "Last updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> timestamp.txt || true

      - name: Create or update pull request
        uses: peter-evans/create-pull-request@v7
        with:
          # Token mit Schreibrechten – GITHUB_TOKEN ist ausreichend
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated-sources
          base: main
          title: "chore: update generated annotations & models"
          commit-message: "chore: update generated annotations & models"
          body: |
            Dieser PR aktualisiert automatisch die generierten Annotations & Models.
          add-paths: |
            annotations/**
            models/**
          # Aktiviert das Auto-Merge direkt nach grünem CI-Check
          auto-merge: true
          merge-method: squash
          delete-branch: false
