name: Test Auto-PR & Merge

# Manuelles Auslösen und zusätzlich alle 5 Minuten (zum Testen)
on:
  workflow_dispatch:

permissions:
  contents: write           # für checkout & commit
  pull-requests: write      # für PR erstellen und mergen

jobs:
  generate-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate or update files
        run: |
          # Beispiel: Timestamp aktualisieren
          echo "Last updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> timestamp.txt

      - name: Create or update pull request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: generated-sources
          base: main
          commit-message: "chore: update timestamp.txt"
          title: "chore: update timestamp.txt"
          body: |
            Dieser PR aktualisiert automatisch die timestamp.txt.
          add-paths: |
            timestamp.txt
          delete-branch: false

      - name: Enable GitHub Auto-Merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
