# .github/workflows/ci-check.yml
name: CI Check

# Trigger bei jedem PR gegen main
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read        # für checkout
  pull-requests: write  # optional, falls du später das PR-Status-API nutzen willst

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
